### ISSUE TITLE
Hi. Thanks for the great work.

### ISSUE THREAD

**Issue by wjun0830** [ReXTime/ReXTime#1]
Hi Jr-Jen.

First of all, thanks for the great work REXTIME. 
However, while reading the paper, I had a question about the performances between methods with conv-based decoder (UniVTG) and detr-based decoder (CG-DETR).
As the performances seem to be compared between the pretrained UniVTG and CG-DETR without pretraining, it is very hard to compare the two.

It would be helpful if the authors provide performance comparison with w/o pretraining settings for both models or w/ pretraining.

For CG-DETR, we have now uploaded the pretrained checkpoint for CG-DETR that employs the pretraining phase of UniVTG [here](https://drive.google.com/drive/folders/1iH4Jfg_5rDA-N1nkg_iqRk-mIcmQblQW) (model_e0009.ckpt).

With the checkpoint, we provide script to load the pretrained weights
```
bash cg_detr/scripts/train.sh --num_dummies 45 --num_prompts 1 --total_prompts 10 --max_q_l 75 --resume pt_checkpoints/model_e0009.ckpt --seed 2018
```

It would be awesome if you could provide the comparison between DETR-based and conv-based methods with the same settings on the proposed benchmark.

Thank you.
Best.

**Comment by ReXTime** [comment]
Hi,

Thank you very much for your interest in our work and for raising this important point.

We appreciate your feedback regarding the performance comparisons between UniVTG and CG-DETR. We understand the difficulty in comparing these models due to the differences in pretraining.

Unfortunately, we were unable to locate the link to the pretrained weight in the official GitHub repository, so we opted to use the weight trained on QVHighlights for our initial evaluations. We are committed to providing a fair comparison and will update the performance numbers on our arXiv release using the pretrained weight you have now provided.

We encourage further evaluation of various methods and hope to see more submissions to our leaderboard after its release.

Thank you again for your valuable input.

Best regards,
Jr-Jen

**Comment by ReXTime** [comment]
Hi,

Thank you for your interest in our work on REXTIME. We appreciate your insightful question regarding the performance comparison between the conv-based decoder (UniVTG) and the DETR-based decoder (CG-DETR).

We understand the importance of a fair comparison and acknowledge the difficulty without access to the pretrained weights from the official GitHub repository. Consequently, we used weights trained on QVHighlights for our evaluation.

After discussing with my advisor, we would like to invite you to submit the evaluation results using the provided pretrained weights to our leaderboard once it is released. Our priority now is to release the evaluation server, which we aimed to release before 7/16. Before the release, we can help evaluate if you provide us with the submission result JSONL.

We are more than happy to assist you throughout this process and would love to collaborate further to ensure a comprehensive evaluation of these methods. Additionally, we are willing to update the score on the arXiv release after submission.

Please feel free to reach out to me via email at r12942106@ntu.edu.tw for any further discussion or assistance.

Best regards,
Jr-Jen

**Comment by wjun0830** [comment]
Sure, I appreciate it!
